<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>cdl</string>
	</array>
	<key>name</key>
	<string>CDL</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>//</string>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>comment.line.cdl</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.cdl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>,</string>
			<key>name</key>
			<string>comment.punctuation.comma.cdl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(object|external|List)\b</string>
			<key>name</key>
			<string>keyword.reserved.cdl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(true|false)\b</string>
			<key>name</key>
			<string>string.boolean.cdl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(-|\.)?\b[0-9]+(\.[0-9]+)?\b</string>
			<key>name</key>
			<string>constant.numeric.cdl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\+|-|\*|/|%|=|!|\^|~|\||\?|&lt;|&gt;|&amp;</string>
			<key>name</key>
			<string>keyword.operator.cdl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\w+(?=\s*:)</string>
			<key>name</key>
			<string>meta.tag.cdl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(int|integer|int64|double|float|boolean|string|char)\b</string>
			<key>name</key>
			<string>support.function.cdl</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.cdl</string>
	<key>uuid</key>
	<string>BFE61B62-1202-4839-BA42-CF5CA534EFA6</string>
</dict>
</plist>
